name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉取代码
    - uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. 代码规范检查 (Linting)
    # 这步会让面试官觉得你代码风格很好
    - name: Lint with flake8
      run: |
        # 检查是否有语法错误
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # 5. 测试 Docker 构建 (确保镜像能打包成功)
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag sneaker-bot:latest